
services:


  api-gateway:
    build: ./backend/api-gateway
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    depends_on:
      - authenticationservice
      - chatservice



  authenticationservice:
    build: ./backend/services/authenticationService
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend/services/authenticationService:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - kafka
    env_file:
      - ./backend/services/authenticationService/.env



  chatservice:
    build: ./backend/services/chatService
    command: npm run dev
    ports:
      - "4001:4001"
    volumes:
      - ./backend/services/chatService:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - kafka
    env_file:
      - ./backend/services/chatService/.env

  notificationservice:
    build: ./backend/services/notificationService
    command: npm run dev
    ports:
      - "4002:4002"
    volumes:
      - ./backend/services/notificationService:/app
      - /app/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./backend/services/notificationService/.env

  presenceservice:
    build: ./backend/services/presenceService
    command: npm run dev
    ports:
      - "4003:4003"
    volumes:
      - ./backend/services/presenceService:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - kafka
    env_file:
      - ./backend/services/presenceService/.env



  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db



  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka

    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"



volumes:
  mongo-data: