version: "3.9"
services:
  api-gateway:
    build: ./backend
    command: node api-gateway/server.js
    ports:
      - "8080:8080"
    depends_on:
      - authenticationservice
      - chatservice
    
  authenticationservice:
    build: ./backend
    command: node services/authenticationService/server.js
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/services/authenticationService/.env
      
    
  chatservice:
    build: ./backend
    command: node services/chatService/server.js
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
    env_file:
      - ./backend/services/chatService/.env
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka

    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

volumes:
  mongo-data:
    


